pyresample/kd_tree.py
pyresample/test/test_kd_tree.py

I have a program that worked okay until I installed pykdtree.  It seems to be more picky about data types, so I added this one-line change to work around the problem.
Here's an example of a traceback I got illustrating the issue:
```
File "/usr/local/lib/python2.7/site-packages/pyresample-1.1.5-py2.7.egg/pyresample/image.py", line 279, in resample
segments=self.segments)
File "/usr/local/lib/python2.7/site-packages/pyresample-1.1.5-py2.7.egg/pyresample/kd_tree.py", line 101, in resample_nearest
reduce_data=reduce_data, nprocs=nprocs, segments=segments)
File "/usr/local/lib/python2.7/site-packages/pyresample-1.1.5-py2.7.egg/pyresample/kd_tree.py", line 259, in _resample
segments=segments)
File "/usr/local/lib/python2.7/site-packages/pyresample-1.1.5-py2.7.egg/pyresample/kd_tree.py", line …
```

Fix possible type mismatch with pykdtree.

---

.travis.yml
pyresample/test/test_kd_tree.py
requirements.txt

And catch the rest of the warnings. Check if there is only one warning collected, and
whether it contains the relevant message ('possible more than 8 neighbours found'). This patch is necessary for python 2.7.9 and newer

[tests] Skip deprecation warnings in test_gauss_multi_uncert

---

appveyor.yml

@davidh-ssec This fixes the import error. Scipy was not installed and the `ImportError: Either pykdtree or scipy must be available` was hidden in shell output.
The tests start to run now but a few still ERROR. See https://ci.appveyor.com/project/cpaulik/pyresample/build/1.0.8/job/hnuud6mc9yftxld2 or the build of this PR.

Fix Windows CI import Error

---

setup.py

Prior to version 3.2 setuptools would not recognize correctly the language of `*.cpp` extensions and would assume it's `*.c` no matter what. Version 3.2 of setuptools fixes that.

Specify minimum version of setuptools

---

pyresample/kd_tree.py
pyresample/test/test_geometry.py
pyresample/test/test_kd_tree.py
setup.py

In numpy 1.13 it is illegal to index an array with a boolean array of a different size. In `kd_tree.py:get_sample_from_neighbour_info` there is a count array of shape `(N * M, 1)`. When resampling is passed multiple channel arrays `(N, M, 3)` the standard deviation and other related arrays have shape `(N * M, 3)`. When passed a single channel they are `(N * M,)`. The count array is used to index in to these stddev and other arrays. In 1.13 this causes an error.
Previously the indexing looked like `v1 = norm[new_valid_index]` which converted a `(N * M, 3)` array in to a `(N * M,)` array by taking only the first channel. This is equivalent to `v1 = norm[new_valid_index, 0]` and is reflected in these fixes.
This PR should fix all of these issues. It also does additional testing on the stddev …

Fix numpy 1.13 compatibility

---

.travis.yml
pyresample/test/test_utils.py
pyresample/utils.py
setup.py

Parse multiple area files

---

pyresample/test/test_ewa_ll2cr.py
pyresample/test/test_utils.py
pyresample/test/utils.py
pyresample/utils.py

Fix #56.
Questions:
1. Should `SwathDefinition` be allowed too?
2. See #56 for my questions about what the expected use of these functions is. Does the target have to be a subset of the source?
TODO:
1. Fix docstring in functions

Fix GridDefinition as permitted definition in preprocessing utils

---

pyresample/test/test_utils.py
pyresample/utils.py

In my SCMI NetCDF4 writer that I'm making for satpy (https://github.com/pytroll/satpy/pull/67) I need access to the PROJ.4 `a` and `b` parameters (equatorial and polar radius) of the dataset being remapped. However, if a PROJ.4 string/dict is specified using a datum and ellps the `a` and `b` parameters are not easily accessible. This PR adds a utility function for checking pyproj for the ellipsoid parameters and computed `a` and `b` from them if needed.

Add 'proj4_radius_parameters' to calculate 'a' and 'b' from ellps

---

pyresample/utils.py

Area definition files were not closed in the current yaml and .ini config file readers. This PR adds context managers around the file `open()`s so that the files are properly closed.

Use context manager to open area definition files

---

pyresample/test/test_image.py

This PR reduces the memory required to run the unit tests for pyresample.image.ImageContainerBilinear class.
The reduction in memory use comes from two roughly different sources:
1. smaller target area
2. less neighbours to search
The resulting changes in the test results have been updated.
Fixes #80

Reduce the memory use for ImageContainerBilinear tests

---

.travis.yml
pyresample/bilinear/__init__.py

This PR fixes how the invalid coordinates were handled in bilinear interpolation, indicated by deprecation warning raised by Numpy. If there's a better way of doing this (compare to the original version), I'm happy to update the PR.
Also UserWarning about possible extra neighbours inside search radius is now suppressed, as the number of retrieved neighbours is more or less static.

Fix bil mask deprecation

---

pyresample/bilinear/__init__.py
pyresample/test/test_bilinear.py

This PR reshapes the output data to correspond to target area definition and the number of "channels"/datasets that are resampled.
Fixes #72

Fix output shape of resample_bilinear()

---

pyresample/grid.py
pyresample/test/test_grid.py

Fix #87 
Use numpy.ma version of row_stack to prevent loosing the mask of large images (rows > cut_off).

Fix masks in grid.get_resampled_image

---

pyresample/kd_tree.py
pyresample/test/test_bilinear.py
pyresample/test/test_kd_tree.py

SatPy produces `SwathDefinition`s with masked array lon/lats. This causes an exception in the `valid_output_index` calculation where eventually it can become a masked array with out a `._mask` due to a `np.append` call. Bottom line, this PR makes sure that the `valid_output_index` is a plain boolean array.

Fix kdtree when target lons/lats are masked arrays

---

pyresample/test/test_geometry.py

No new test has been added. A failing test has been fixed.

Fix test_get_array_hashable on big-endian machines (closes #90)

---

docs/source/plot.rst
docs/source/swath.rst
pyresample/__init__.py
pyresample/geometry.py
pyresample/kd_tree.py
pyresample/test/test_geometry.py
pyresample/test/test_utils.py
pyresample/utils.py
setup.py

This optimizes how dask arrays are computed and used in the nearest neighbor resampling. It reduces the usage so that dask arrays *should* only be computed once and when possible should share as many calculations as possible. Two things that should be looked at:
Note the backwards compatibility breaking change this PR includes where `BaseDefinition` no longer checks lon/lat input arrays for -180/180,-90/90 validity since doing that with dask arrays would be a huge waste of time and it is a huge waste of computation time even for normal numpy arrays. The usual use case is a user who already has valid inputs.

Optimize xarray

---

setup.py

This fixes the minimum version of pyproj needed by pyresample

Provide the minimum version of pyproj needed

---

pyresample/data_reduce.py
pyresample/test/__init__.py
pyresample/test/test_data_reduce.py
pyresample/test/test_kd_tree.py

This PR fixes the gap appearing at the poles for areas containing a pole

Revert "Fix data reduction when poles are within area"

---

pyresample/geometry.py
pyresample/kd_tree.py

This PR allows the dask methods to specify a 2D chunk size. This should allow for the best performance when chunk size is shared across arrays.

Allow chunk size in dask methods to be 2D

---

pyresample/geometry.py
pyresample/test/test_geometry.py

Fix omerc dynamic area computation to choose the best angle.

Make azimuth angle for omerc dynamic areas more robust

---

.stickler.yml
pyresample/geometry.py
pyresample/test/test_geometry.py

Implement area-slicing for geos-based areas.

Geos area reduction

---

pyresample/geometry.py

Add hashing to StackedAreaDefinitions

---

docs/source/swath.rst
pyresample/bilinear/__init__.py
pyresample/bilinear/xarr.py
pyresample/ewa/__init__.py
pyresample/geometry.py
pyresample/test/test_bilinear.py
pyresample/test/test_geometry.py
pyresample/test/test_grid.py

There was a strange error I was getting when my destination (target) area for resampling in satpy was larger than the source area. During the resampling step of slicing away source data that wasn't needed I was running in to index errors. This PR fixes the two errors I encountered while fixing my use case and addresses one duplicate property in the area definition class.
First, it is possible for boundary intersections to be invalid in one of the projections so we have to make sure to take `np.ma.min(x)` instead of just `x.min()` where the latter could potentially returned masked values.
Second, the `get_xy_from_X` type methods had an off-by-one error where the index returned could be equal to the length of the array when that number is actually invalid (max index is length of array - 1). …

Fix get_area_slices edge case when target is larger than source

---

.travis.yml
pyresample/boundary.py
pyresample/geometry.py
pyresample/test/test_geometry.py

If two areas use the same projection then you should be able to slice using them.

Fix area slices not working for non-geos projections

---

pyresample/test/test_spherical.py

The pyresample 1.9.3 Debian package failed to build on some architectures ([arm64](https://buildd.debian.org/status/fetch.php?pkg=pyresample&arch=arm64&ver=1.9.3-1&stamp=1528790874&raw=0), [i386](https://buildd.debian.org/status/fetch.php?pkg=pyresample&arch=i386&ver=1.9.3-1&stamp=1528790751&raw=0), [ppc64el](https://buildd.debian.org/status/fetch.php?pkg=pyresample&arch=ppc64el&ver=1.9.3-1&stamp=1528790956&raw=0), [s390x](https://buildd.debian.org/status/fetch.php?pkg=pyresample&arch=s390x&ver=1.9.3-1&stamp=1528790549&raw=0), [powerpc](https://buildd.debian.org/status/fetch.php?pkg=pyresample&arch=powerpc&ver=1.9.3-1&stamp=1528790853&raw=0), [ppc64](https://buildd.debian.org/status/fetch.php?pkg=pyresample&arch=ppc64&ver=1.9.3-1&stamp=1528791735&raw=0), …

Fix TestArc failure on some architectures.

---

docs/source/installation.rst
pyresample/__init__.py
pyresample/geometry.py
pyresample/kd_tree.py
pyresample/test/test_kd_tree.py
setup.py

Also remove scipy kdtree as an option and removed get_capabilities. Needs tests and documentation. Also will need pykdtree 1.3.1 when it is released.

Add option to provide KDTree's 'mask' argument when querying

---

pyresample/geometry.py

Fix log message not to rely on the proj key

---

pyresample/_cartopy.py

The warning was supposed to show that a recent version of cartopy should have the PROJ.4 -> CRS functionality, but this still hasn't been added to cartopy so the warning is confusing.

Remove warning about cartopy 0.17

---

pyresample/test/test_utils.py
pyresample/utils.py

Legacy file format was producing area definition objects where PROJ.4 dictionaries had numeric values (lon_0, lat_0, etc) that were being stored as strings in the AreaDefinition. This is undesired in 99% of the use cases that I can think of. This PR makes it so any time (at least in the utility functions) a PROJ.4 string is converted to a dictionary the parameters are converted to floats when possible.
This was pointed out by @yufeizhu600 and @goodsonr as an issue in some satpy use cases.

Fix area parsing code to convert PROJ.4 parameters to float if possible

---

.travis.yml
appveyor.yml
pyresample/geometry.py
pyresample/test/test_geometry.py

Non-contiguous area definitions are now not concatenable

---

pyresample/kd_tree.py
pyresample/test/test_kd_tree.py

Fix dtype preservation for kdtree resampling

---

appveyor.yml
pyresample/geometry.py
pyresample/test/test_geometry.py
pyresample/test/test_swath.py

There was currently only a `get_proj_vectors_dask` method, but since we typically use dask arrays with xarray and xarray coordinates *have* to be computed and proj vectors are typically used as xarray DataArray coordinates it makes more sense to me to just provide a numpy array version of the method. Also if using dask's ProgressBar context manager using dask arrays as coordinates results in multiple progress bars for each coordinate that has to be computed. This can be confusing to some users.
Additionally this PR includes a refactor of all of these associated methods (coords/vectors) to reuse as much code as they can. This includes deprecating the `_dask` versions of the few methods that exist or at least adding a deprecation warning for them.
This PR also includes adding rotation …

Refactor and deprecate geometry "*_dask" methods

---

pyresample/utils.py

In some cases, parsing an areas.def file in the old format raises a yaml.parser.ParserError, which has therefore been added to the yaml.scanner.ScannerError.

Added another possible error in parse_area_file

---

pyresample/utils/__init__.py

In #156 I forgot to add `parse_area_file` as one of the deprecated/moved functions. This is breaking satpy and other pytroll packages. This adds the wrapper function to fix this.

Add parse_area_file wrapper function to pyresample.utils

---

pyresample/utils/__init__.py

The 'typing' module was used to import the `Mapping` class for a small utility function. This was causing compatibility issues for environments with python <3.5. The `Mapping` object should be available from the `collections` module in all supported versions of python.

Fix 'typing' import with 'collections' for python 2 compatibility

---

requirements.txt

Not used and only references basemap which is deprecated. @pytroll/core let me know if I'm missing something.

Delete unused requirements.txt file

---

pyresample/area_config.py
pyresample/test/test_files/areas.yaml
pyresample/test/test_utils.py

YAML parsing was assuming meters for units even for latlong projections.
@pnuu @wroberts4 Can you verify that this fixes the issue brought up on slack.

Fix yaml area loading when projection is latlong (units degrees)

---

pyresample/utils.py

Currently entering a radius or pixel_size in degrees when the center is at the poles (and normal lat/long is not the same as the center lat/long) does not yield the expected result. This change makes sure that the x direction is treated the same as the y direction and hence makes a square when both the x and y dimensions are equal.

Fix create_area_def around poles

---

appveyor.yml
pyresample/area_config.py
pyresample/kd_tree.py

This PR also include other small fixes:
- remove appveyor on python 2.7
- fix the pyyaml deprecation warnings
- replace da.atop with da.blockwise

Fix attributes copy after resampling to be a deepcopy

---

pyresample/area_config.py
pyresample/test/test_geometry.py

Allow create_area_def to work with incomplete proj dicts to create DynamicAreas

Allow create_area_def to work with incomplete proj dicts to create DynamicAreas

---

pyresample/_cartopy.py
pyresample/test/test_geometry.py

When computing the ``threshold`` property in class ``_PROJ4Projection``, take into account that lower left x/y can be larger than upper right x/y if the area is flipped N-S and/or E-W.
@djhoese I don't know what this threshold is actually used for by cartopy, but it solves the coastlines issue. Can you please check which of the other properties using ``self.bounds`` need to be adapted?

Fix _PROJ4Projection threshold

---

MANIFEST.in
README.md
docs/source/index.rst

Small typos in the README and index page descriptions

Fix typos in README and index page

---

pyresample/geometry.py
pyresample/test/test_geometry.py

When the first or last line of the lons and lats of a swath contains nans, the dynamic omerc parameter computation was crashing. This PR resolves the issue by finding the first and last non-nan data in that case.

Fix dynamic omerc parameter computation to survive nans

---

pyresample/geometry.py
pyresample/test/test_geometry.py

This PR implements striding and aggregation for a couple of Definition objects.

Implement striding and aggregation for Swath- and AreaDefinitions

---

pyresample/area_config.py

Document the arguments for get_area_def in the same order in which they
are defined.

Fix argument order in get_area_def doc

---

pyresample/geometry.py
pyresample/test/test_geometry.py

Fix bb computation to generate areas with equal h and v resolutions

---

pyresample/area_config.py
pyresample/test/test_files/areas.yaml
pyresample/test/test_utils.py

I wanted to make a quick dynamic area definition in my areas.yaml file like this:
```
test_dynamic_resolution:
description: Dynamic with resolution specified in meters
projection:
proj: lcc
lon_0: -95.0
lat_0: 25.0
lat_1: 25.0
ellps: WGS84
resolution: [1000, 1000]
```
However, this didn't work because `resolution` wasn't being passed to the area definition creation. It seems that my fixes to get this to work haven't broken anything. I'm 90% sure this was supposed to work before so I'm not sure it needs to be documented any more than it already is. Additionally I changed it so that you don't need to specify `center` to convert a value in "degrees" to "meters" (makes `center` default to `(0, 0)`).
I'd like @sfinkens and @wroberts4 to take a look at this if they have the time.

Fix resolution not being passed to DynamicAreaDefinitions

---

pyresample/geometry.py
pyresample/test/test_geometry.py

I noticed that slicing an AreaDefinition with `[::4, ::4]` I was getting unexpected sizes like a 6000x10000 area becoming a 1499x2499 area. This PR fixes this off-by-one issue.

Fix striding slicing in AreaDefinition

---

docs/source/API.rst
docs/source/index.rst
docs/source/swath.rst
pyresample/bucket/__init__.py
pyresample/test/__init__.py
pyresample/test/test_bucket.py
pyresample/test/utils.py
setup.py

This PR adds few methods to do "drop-in-a-bucket" resampling for calculating
- averages (average of all the values hitting a bin)
- hit-counts (number of values hitting a bin)
- fractions of different categorical values (e.g. water fraction of a bin)
when aggregating high resolution data to a lower resolution grid.

Add bucket resampling

---

pyresample/geometry.py
pyresample/test/test_geometry.py

This PR converts `AreaDefinition.to_cartopy_crs().bounds` from degrees to radians for the `latlong` projection. At the moment they are specified in degrees which leads to tiny coastlines being displayed in the middle of the image.
```python
In [1]: import pyresample 
...: import matplotlib.pyplot as plt 
...: import numpy as np 
...:  
...: area_def = pyresample.AreaDefinition( 
...:     area_id='test', 
...:     description='test', 
...:     proj_id='test', 
...:     projection={'proj': 'latlong', 'lon0': 0}, 
...:     width=360, 
...:     height=180, 
...:     area_extent=(-180, -90, 180, 90), 
...: ) 
...: crs = area_def.to_cartopy_crs() 
...: crs.bounds …
```

Fix to_cartopy_crs for latlong projections

---

pyresample/bucket/__init__.py
pyresample/test/test_bucket.py

Currently the bucket average counts NaNs in the data as valid observations. For example values [1, 2, 3, np.nan] are averaged to (1+2+3) / 4 = 1.5 instead of (1+2+3) / 3 = 2. Here is a snippet to reproduce:
```python
import pyresample.bucket
from pyresample import create_area_def
import numpy as np
import dask.array as da
area_def = create_area_def('my_area',
{'proj': 'eqc', 'lon_0': 0},
center=(0, 0),
width=2, height=2,
resolution=10,
units='degrees')
lons = da.from_array([[0, 0], [0, 0]], chunks=1)
lats = da.from_array([[0, 0], [0, 0]], chunks=1)
data = da.from_array([[1, 2], [3, np.nan]], chunks=1)
resampler = pyresample.bucket.BucketResampler(target_area=area_def,
source_lons=lons,
source_lats=lats)
avg = resampler.get_average(data=data, mask_all_nan=True, fill_value=np.nan).compute() …
```

Exclude NaNs from Bucket Average

---

setup.py

This PR adds a limitation for Numpy version when Python 2.7 is used. Numpy version 1.7.0+ support only Python 3, and thus lower version is needed for Python 2 installation.

Add Numpy version limitation for Python 2

---

pyresample/bilinear/xarr.py

This is a hot-fix for that removes a stray call to `da.from_array()` for an dask array causing a crash.

Remove extra conversion to dask array

---

pyresample/test/test_utils.py
pyresample/utils/_proj4.py

Providing a=b in the proj definition gets converted to R. We add support for this parameter.

Fix proj4 radius parameters for spherical cases

---

pyresample/geometry.py
pyresample/test/test_geometry.py

Fixes an issue some users have been running in to recently with newer version of PROJ. Pyproj/PROJ are interpreting `+a` and `+b` being defined as being the same thing as `+ellps=` when they match an ellipsoid. This was causing issues in `get_geostationary_angle_extent` where it was using the `proj_dict` and assuming `a` and `b` existed.
Side note: I wanted to try to use the `crs.ellipsoid.semi_major_metre` and `crs.ellipsoid.semi_minor_metre` but, at least on my machine, PROJ only provides the minor/polar radius if it is part of the ellipsoid definition (often the flattening is defined along with `a`). I made this pyproj issue to ask if there is a good way to get this information from pyproj instead of computing it ourselves in pyresample: https://github.com/pyproj4/pyproj/issues/457

Fix get_geostationary_angle_extent assuming a/b definitions

---

pyresample/geometry.py
pyresample/test/test_geometry.py

This helps fix some of the issues with satpy generic_image reader tests failing. Basically rasterio/pyproj will sometimes add a `+towgs84=0,0,0,0,0,0,0` to the PROJ/CRS definition. This is generally fine as it doesn't change the specification (the projection is the same projection) but it is a problem in that doing a CRS equality will now fail. Right now we do AreaDefinition equality based on `proj_str` and one will have the `towgs84` and the other might not. In the long run we should use `CRS(proj_str) == `CRS(other.proj_str)` but this also fails with this `towgs84` difference. I made an issue on pyproj but as expected this is handled by the lower-level PROJ library so it would take longer and be more involved of a change to make it work (see …

Fix proj_str returning invalid PROJ strings when towgs84 was included

---

pyresample/geometry.py

This PR makes the computation of the uniform shape of areas (case of data-dependent areas) more efficient.
This is still not very efficient in the grand scale of things, but improves over the last iteration.
Next step is maybe to use a pre-computed bounding box when available (see satpy issue here: https://github.com/pytroll/satpy/issues/933)

Make the uniform shape computation more effective for dask arrays

---

.pre-commit-config.yaml
pyresample/utils/__init__.py

Fix deprecation warning for abc classes

Fix deprecation warning for abc classes

---

pyresample/spherical.py
pyresample/test/test_spherical.py

When spherical.SphPolygon is returning an instance of a SphPolygon (f.x in _bool_oper) it should pass the radius of it self. So area computations are consistent.

Fix inconsistent radius

---

pyresample/area_config.py

Pyresample's area loading methods have accepted multiple files for a while, but it wasn't documented in the higher level functions.

Update load_area docstring to mention that multiple files are allowed

---

pyresample/_spatial_mp.py
pyresample/test/test_spatial_mp.py

The main problem was the casting of pi/180 to the same type as the latitude-longitude data. In the case of integer data it is cast to zero.  Current solution uses np.deg2lats in case the pi/180 was cast to zero.

Fix cartesian coordinate calculations when lon/lats are integers

---

pyresample/geometry.py
pyresample/test/test_geometry.py

Respect dtype when get_lonlats provide dask array.

Respect dtype when get_lonlats provide dask array

---

pyresample/gradient/__init__.py
pyresample/resampler.py
pyresample/test/test_gradient.py

pyximports make the import of gradient resampler fail if cython isn't installed

Remove pyximports from gradient search

---

docs/source/conf.py
pyresample/geometry.py
pyresample/test/test_geometry.py

First noticed by @zxdawn, some Satpy datasets have a `resolution` attribute but it is `None`. This PR fixes this so it doesn't raise an exception.
Also includes docstring fixes for DynamicAreaDefinition. We don't have sphinx document the `__init__` method separately so the docstring for DynamicAreaDefinition was missing in the readthedocs pages.

Fix SwathDefinition geocentric_resolution when resolution is None

---

pyresample/geometry.py
pyresample/test/test_geometry.py

Omerc bounding box computation was using WGS84 as an ellps, which causes problems, see
https://github.com/pytroll/satpy/issues/1002

Make omerc bouding box use sphere as ellps

---

setup.cfg

Fix so that it is possible to make an rpm package for Python 3 (only)

Fix for python3 rpm-build

---

.travis.yml

There was a problem between libtiff and libwebp on conda-forge. I added a restriction in the past, but this should now be fixed on conda-forge's side.

Undo libtiff version restriction on travis

---

pyresample/geometry.py

In the AreaDefinition docstring, fix the order in which the parameters
are document to match the order in which they are defined, and clarify
that the rotation is optional.
Fixes #261.

Fix parameter order in AreaDefinition docstring

---

docs/source/conf.py
docs/source/geometry_utils.rst
pyresample/geometry.py
pyresample/test/test_files/areas.yaml
pyresample/test/test_geometry.py
pyresample/test/test_grid.py
pyresample/test/test_utils.py
pyresample/test/utils.py
pyresample/utils/_proj4.py

This PR is an effort to resolve the issues discussed in:
https://github.com/pyproj4/pyproj/issues/589
https://github.com/pytroll/satpy/issues/1114
The summary of these issues is that the pyproj `CRS` object is not thread-safe. If you access one from multiple threads you can get strange corrupt strings and bytes. I've found one case in all of satpy, pyresample, and trollimage (I think) where we explicitly pass a CRS or Proj object to a dask function (map_blocks, blockwise, delayed) and that's what this PR fixes (call to `invproj` with a `CRS` object). There is an additional usage in the EWA resampling in Satpy where an AreaDefinition is passed to a delayed function. I would like to be able to confidently pass AreaDefinitions between threads so that issue is also addressed here.
The main …

Switch to storing CRS WKT in AreaDefinitions instead of the CRS object

---

pyresample/kd_tree.py
pyresample/test/test_kd_tree.py

This PR removes a type check for the `fill_value` keyword argument of the `get_sample_from_neighbour_info` function in `pyresample/kd_tree.py`. The previous type check was limiting the fill value to being either `None`, or Python standard `int` or `float` types. This was not compatible with `numpy` data types (e.g. `np.uint8`, `np.float32`, etc).
As a result of this change, if an incompatible fill value (such as a string) is supplied to `get_sample_from_neighbour_info`, the function will fall back on a `ValueError` raised by `numpy`.

Remove type check for nearest neighbour fill value.

---

pyresample/bucket/__init__.py
pyresample/test/test_bucket.py

The bucket assignment in the bucket resampler seems to be off by half a pixel. This PR provides a fix. 
Example:
```python
from pyresample import create_area_def
from pyresample.bucket import BucketResampler
import dask.array as da
import numpy as np
area = create_area_def(
area_id='test',
projection={'proj': 'latlong'},
center=(0., 0.),
width=4,
height=4,
resolution=10.0
)
lons = da.from_array(np.array([-15, -5, 5, 15]), chunks=2)
lats = da.from_array(np.array([-15, -5, 5, 15]), chunks=2)
data = da.from_array(np.array([1, 2, 3, 4]), chunks=2)
resampler = BucketResampler(source_lats=lats,
source_lons=lons,
target_area=area)
count = resampler.get_count()
```
Output with current master:
```
[[0 0 0 1]
[0 2 0 0]
[0 0 0 0]
[1 0 0 0]]
```
Output with this PR:
```
[[0 0 0 1]
[0 0 1 0]
[0 1 0 0] …
```

Fix bucket assignment

---

pyresample/geometry.py
pyresample/test/test_geometry.py
pyresample/test/test_kd_tree.py

This is a major fix for how nearest neighbor resampling works by default. In a previous PR (#225), I had added a `geocentric_resolution` method which could be used to come up with a best guess for the `radius_of_influence` of nearest neighbor resampling. However, all of my tests were based on square areas. While investigating a complaint by a coworker, I realized that `geocentric_resolution` actually depends on the size of the X and Y dimension.
The code I had did the following:
1. Create a horizontal midline and vertical midline of coordinates.
2. Calculate the geocentric distance along the points on those lines.
3. Take the histogram of all of those distances.
4. Take the largest bin (the one with the most points) and average the edge values.
The issue with this is that the histogram, …

Fix geocentric resolution favoring one area dimension over the other

---

pyresample/geometry.py
pyresample/test/test_geometry.py
pyresample/test/test_kd_tree.py

This fixes a segmentation fault for Satpy data reduction when the source area is flipped and GEO data has space surrounding the full disk data. In this case `pykdtree` was passed coordinates that were `inf` which causes segmentation fault.

Fix calculating area slices for flipped projections

---

pyresample/geometry.py
pyresample/test/test_geometry.py

This PR adds the possibility to create AreaDefintions from EPSG codes that include an area of use.
The usage is for example:
`sweref = AreaDefinition.from_epsg('3006', 1000)`
to get the SWEREF99 TM area in 1km resolution.
Some example of imagery generated with satpy for epsg 3006 and 3034:

Create AreaDefinition from epsg codes

---

pyresample/geometry.py
pyresample/test/test_utils.py
pyresample/utils/__init__.py

This PR makes sure that the `slice(start, stop, step)` has correct sign for the `step` argument when `start > stop` when slicing the area.

Check area slices for correct step

---

docs/README.md

Small leftover `-P` used during testing of #279.

Remove unnecessary -P flag from the docs readme

---

pyresample/geometry.py
pyresample/test/test_geometry.py

When comparing an AreaDefinition for equality against a type that isn't
an AreaDefinition, return False rather than raising an AttributeError.
Fixes #287.

Fix type-alien areadef comparisons

---

pyresample/geometry.py
pyresample/test/test_geometry.py

This PR fixes a bug observed in the `AreaDefinition `method `colrow2lonlat`. The function was working properly only for square areadefs, while returning wrong values for other areas. 
To reproduce:
```python
from satpy.resample import get_area_def
from satpy.scene import Scene
def lonlat2colrow2lonlat(lon_in, lat_in, area_def, desc):
"""Checks the reciprocity of lonlat2colrow and colrow2lonlat."""
col, row = area_def.lonlat2colrow(lon_in, lat_in)
lon_out, lat_out = area_def.colrow2lonlat(col, row)
print("\nLon out "+desc+": ", lon_out)
print("Lat out "+desc+": ", lat_out)
return
lon_in = 30
lat_in = 40
print("Lon in: ", lon_in)
print("Lat in: ", lat_in)
area_def = get_area_def("seviri_0deg")
lonlat2colrow2lonlat(lon_in, lat_in, area_def, 'seviri_0deg')
area_def = get_area_def("eurol") …
```

Fix colrow2lonlat working only for square areadefs

---

pyresample/bilinear/xarr.py
pyresample/test/test_bilinear.py

Since some recent changes in Satpy resampling a of mix of float and integer datasets (e.g. when using `BackgroundCompositor`) in to one output was broken in two ways in `XArrayResamplerBilinear`.
1. `fill_value` was set to `np.nan` even for the integer dataset
2. if one of these datasets had `RGBA` and another `RGB` bands, **sometimes** there were problems assigning the correct bands to the output dataset after resampling.
I'm not entirely sure why this happens, but this fixes it.

Fix fill value for integer datasets, fix band assignment

---

.pre-commit-config.yaml
azure-pipelines.yml
docs/source/grid.rst
docs/source/swath.rst
pyresample/bilinear/__init__.py
pyresample/bilinear/xarr.py
pyresample/image.py
pyresample/test/test_bilinear.py
pyresample/test/test_image.py

This is a big refactoring for bilinear interpolation. Most of the bits are also re-used in the legacy Numpy version, but I didn't want to put too much time in pulling out all the parts of `pyresample.bilinear.get_sample_from_bil_info()`.
There will be some renaming and such that can be improved, but I've run out of steam for now :sweat_smile: Suggestions are wellcome!
This refactoring also brings some performance improvements when using pre-computed resampling info. With the script below, using Satpy, I got the following timings:
*EDIT*: Timings updated for latest Satpy `master` (Oct-7 2020) with minimal other load on the laptop.
Pyresample `master` branch
- initial run (`generate=False`): ~3 m 28 s~ 3 m 14 s
- initial run (`generate=True`): ~4 m 42 s~ 4 m 20 s
- reusing the cached …

Refactor bilinear

---

pyresample/test/test_utils.py

Recent pyproj introduced a different naming for the web-mercator projection.
The patch takes into account of the different naming and make all tests pass properly also with new versions of pyproj.
**Edit**: see also https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=949274

Improve compatibility with new pyproj

---

pyresample/geometry.py
pyresample/test/test_geometry.py

Prohibit setting area_extent on AreaDefinition objects.

Make AreaDefinition.area_extent read only

---

pyresample/geometry.py
pyresample/test/test_geometry.py

This PR fixes a bug occurring when `StackedAreaDefinition.get_lonlats()` is called with `chunks` being defined. 
If multiple chunk sizes are defined for the vertical dimension inside a tuple, each chunk size needs to be assigned to each `AreaDefinition` inside the `StackedAreaDefinition`. 
This was previously not implemented and untested, and was causing errors with stacked channels such as the SEVIRI HRV, e.g. as reported in https://github.com/pytroll/satpy/issues/1440 .
Thanks to @djhoese for the discussion about this in Slack this summer (https://pytroll.slack.com/archives/C0LNH7LMB/p1595520556054400)  and the solution proposal, and sorry for the delayed PR!
Closes https://github.com/pytroll/satpy/issues/1440

Fix chunks assignment for stacked areadefs in StackedAreaDefinition.get_lonlats()

---

pyresample/bucket/__init__.py
pyresample/test/test_bucket.py

Remove mask_all_nan kwarg and handle input fill_values in average bucket resampler, introduce skipna in get_average and get_sum

---

.coveragerc
.github/workflows/ci.yaml

Coveralls keeps reporting 0. It may be that it expects a certain file format to be generated. This PR is me figuring it out.

Fix coveralls reporting from github actions

---

pyresample/bucket/__init__.py

A simple fix of the wrong varname used in bucket doc.

Fix wrong varname in bucket doc

---

pyresample/area_config.py

In the create_area_def documentation, mention that a pyproj CRS object can
be passed instead of a proj4 dict or proj4 str.

Add CRS option to create_area_def docs

---

pyresample/ewa/dask_ewa.py
pyresample/test/test_dask_ewa.py

This was a bug I discovered at the same time I found #342, but had a really difficult time reproducing. The main piece of code that is effected is *only* called when dask determines that it should call the "aggregate" function of the reduction with a specific result from the previous "combination" calls. I was able to force this by making the input one single chunk.

Fix EWA resampling when the result is all fill values

---

pyresample/geometry.py
pyresample/test/test_geometry.py

I had some swath data that crossed over the anti-meridian (-180/180) and when I pass these to a DynamicAreaDefinition with a latlong projection, the result goes around the whole projection (from -180 to 180). My fix checks if we cross the anti-meridian and recalculates the extents of the area so we produce the smallest area possible. It only does this if we aren't going over the poles. So if we original calculate that xmin/xmax is -179.9/179.9, then we recalculate to produce something like 165.0/225.0.
I'm torn on whether or not my fix should be added; either as-is, not at all, or with an extra keyword argument to allow it. On one hand, a projection like `+proj=longlat +datum=WGS84` (your basic EPSG:4326) is defined from -180 to 180 degrees longitude. In my opinion, a coordinate reference …

Fix DynamicAreaDefinition not handling lons over antimeridian

---

docs/source/geometry_utils.rst
pyresample/geometry.py
pyresample/test/test_geometry.py
pyresample/utils/__init__.py

Flipped areas didn't play well with get_area_slices. This PR takes care of it.
This also makes get_xy_from_proj_coords and get_xy_from_lonlats return floats instead of ints, which I think makes more sense. The user can then choose what to do with the results.

Fix get_area_slices for flipped areas

---

docs/source/swath.rst
pyresample/ewa/dask_ewa.py
pyresample/test/test_dask_ewa.py

This sets rows_per_scan to the number of rows in the input data. In my original development of the EWA algorithm in pyresample I made it so if you didn't specify rows_per_scan it would default to the total number of rows in the input data. This means EWA treats the data as one large scan line. This is not how the algorithm is really meant to work, but it seems to produce decent results in some cases. As I rewrote the EWA algorithm to be more dask-friendly, I didn't like this implicit "magic" setting of the parameter when there may be a more optimal value if only the user knew about it. So I made the choice in previous PRs to require the rows_per_scan if the value couldn't be pulled from a `DataArray`s `.attrs` (and it wasn't specified by the user).
This is fine, except it turns out there …

Allow rows_per_scan=0 convenience in EWA resampler

---

pyresample/geometry.py
pyresample/test/test_geometry.py
pyresample/utils/proj4.py

Add better dask handling to DynamicAreaDefinitions

---

pyresample/geometry.py
pyresample/test/test_geometry.py

This addresses #350, by explaining what the fill values are for that function

Fix the documentation of get_array_indices_from_lonlat and add a test

---

.github/workflows/deploy.yaml
codecov.yml

The deploy workflow runs for tags and for github releases. The job that deploys to the main PyPI is only run on github releases ("published" events). The test-pypi upload however runs for both tags and releases. This means that it always fails when we do a git tag followed by a github release as test-pypi doesn't like that we are trying to upload a package that already exists.
This PR should fix that, but I don't have a good way to test it without actually making a release.

Fix test-pypi deploy failing during actual deployment

---

docs/source/conf.py
pyresample/bucket/__init__.py
pyresample/test/test_bucket.py

This PR adds two functions to Bucket: `get_min` and `get_max`.

Add `get_min` and `get_max` to Bucket resampler (experimental)

---

.github/workflows/deploy.yaml
setup.cfg

Make sure that the wheel distributions include the versioneer details correctly. 
N/A ?
Tests for this need to be local for now, 
```bash
python -m build -w
pip install dist/pyresample*.whl
python -c "import pyresample; print(pyresample.__version__)"
```

Fix version number not being preserved in wheels

---

pyresample/test/test_utils.py
pyresample/utils/cf.py

The geostationary projections can be radians, microradians or meters. We need to handle these in `_convert_XY_CF_to_Proj`.

Fix handling of geostationary x/y units in CF conversion

---

pyresample/ewa/dask_ewa.py

As mentioned in #368, tests are now failing with newer versions of dask. The root cause is that dask now accepts/understands receiving a tuple when computing "meta" information. This PR fixes this by explicitly detecting when meta calculations are being done and returning a specific result so dask knows what it is doing.
Since the existing tests were failing, no addiitional tests should be needed.

Fix dask ewa issues with newer versions of dask

---

docs/source/index.rst
docs/source/roadmap.rst

A couple months ago a couple of us have been having "design meetings" to work towards a Pyresample 2.0 design. As part of these meetings we conducted a user survey and got a lot of good responses. After a lot of back and forth we ended up with some important changes and what we think are good interfaces. In order to get the word out there and get more feedback on this I've put together a Roadmap document for the website that people (maintainers and users) can refer to when talking about Pyresample 2.0.
Let me know what you think. I'm not sure how much of this I just assumed from our meetings and how much is what we actually agreed upon. You won't hurt my feelings if you completely disagree. That's the point of this, let's discuss.

Add initial draft of a Roadmap page

---

pyresample/ewa/_ll2cr.pyx
pyresample/test/test_ewa_ll2cr.py

This PR removes an `elif` condition in the `ll2cr_static` method, which would identify when source pixels were at least three quarters of the circumference of the target projection away from the target grid origin x coordinate. Data that satisfied this condition were then incremented by the projection circumference.
For swaths that cross the anti-meridian, this meant data with longitudes greater than three quarters of the target projection circumference were being shifted out of the target grid, and therefore the data were being omitted.

Update EWA ll2cr_static to handle swaths crossing the anti-meridian.

---

pyresample/kd_tree.py
pyresample/test/test_kd_tree.py
pyresample/test/utils.py
setup.cfg

While working on Polar2Grid I noticed that nearest neighbor resampling was computing xarray coordinates when it didn't need to. This code was from before we realized that xarray always computes coordinates (at least 1D coordinates). This PR's changes will mostly be flake8 fixes. I can't believe we haven't edited these files since we adopted pre-commit :cry:.

Remove unnecessary dask computation in 'nearest' resampler

---

pyresample/geometry.py
pyresample/test/test_geometry.py
pyresample/utils/cartopy.py
setup.py

Cartopy 0.20.0 includes updates by @snowman2 so that cartopy's CRS objects are now a subclass of pyproj's CRS class. Somehow this release broke compatibility with pyresample's hacky cartopy conversion where we started getting errors in our tests related to `towgs84` PROJ.4 string parameters being invalid. Something got lost in the CRS -> proj4 dict -> proj4 str -> CRS conversion.
Rather than figure out where this conversion issue was happening, I chose to implement something that I discussed in the cartopy issue here (https://github.com/SciTools/cartopy/issues/813). Instead of tricking cartopy into accepting arbitrary PROJ.4 information, this uses the new pyproj/cartopy CRS functionality to pass pyresample's pyproj CRS object directly to cartopy. This PR acts as a test for this …

Fix compatibility with cartopy 0.20.0+

---

docs/source/geometry_utils.rst

I noticed the formatting was wrong while reading the docs today. Looks like the indentation is a little messed up.

Fix indentation on geometry utils page

---

pyresample/geometry.py
pyresample/spherical.py
pyresample/test/test_geometry.py
pyresample/test/utils.py

This is a continuation of #385. That PR originally started as a "my data isn't clockwise so things are incorrect". I then found out that the fake data I was using was actually incorrect and didn't match the real world data I was trying to work with. So switching to 64-bit floats fixed that issue.
Now I'm working with other real world data (MiRS algorithm output) where the lon/lat arrays have their first element (row 0, column 0) in the south-west corner which results in the `get_bbox_lonlats` producing coordinates in a counter-clockwise path. This PR fixes this issue in a very similar way as my original fix #385 except for a few important points:
1. I now only use the first two pixels to determine if the first and second side are in increasing in value. This should get around some of the …

Fix SwathDefinition get_bbox_lonlats returning counter-clockwise coordinates

---

pyresample/_spatial_mp.py
pyresample/bilinear/xarr.py
pyresample/bucket/__init__.py
pyresample/future/resamplers/nearest.py
pyresample/kd_tree.py
pyresample/test/test_kd_tree.py
setup.py

With a new production chain I noticed the following depraction warning in the logs:
```python
lib/python3.9/site-packages/pyresample/kd_tree.py:968: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
radius=self.radius_of_influence, dtype=np.int,
```
This PR replaces all the usages of `np.int`, `np.float` and `np.bool` with the preferred versions listed in …

Replace depracated Numpy dtypes

---

.github/workflows/ci.yaml

Python 3.9 wasn't used to run the unit tests. This'll add it, and swap the experimental test runs to it.

Add Python 3.9 to CI runs and use it for the experimental run

---

pyresample/ewa/_fornav_templates.cpp
pyresample/ewa/dask_ewa.py
pyresample/test/test_ewa_fornav.py

This PR fixes a bug that was only obvious with the new dask implementation of the EWA resampler and only with data that had a very large input size. In my Polar2Grid use cases this showed up with the MiRS reader where we set the weight delta max to 100.0 (that's 100 output grid cells). We expect an image like:
But were getting this:
The "feathering" near the top is expected as this data gets to high latitudes and this is a latlong output AreaDefinition. However, the vertical line in the second image is not expected. What is actually happening is that the EWA algorithm was discarding any input pixels that were to the left or below the output grid. The way the dask implementation works means that there are a lot more of these "edge" cases in the middle of the final output image. These …

Fix EWA resampling when input data is larger than the output area

---

pyresample/geometry.py
pyresample/test/test_geometry.py

This is part of my work on the Satpy issue https://github.com/pytroll/satpy/issues/1902. As described in some of the docstrings in this PR, these changes make it so that `get_proj_coords`, the method that returns a 2D X and a 2D Y coordinate array for each pixel of an AreaDefinition, generates the data usings a `map_blocks` call. Previously this data was generated by getting the 1D vectors via `np.arange` and some other math, then passing them to `np.meshgrid` to turn them into 2D vectors. Those series of steps produce an odd series of tasks for dask when the coordinates are used for future work like converting to lon/lat arrays and then using those lon/lats to generate solar zenith angles (for example). The result is that dask has trouble scheduling the future tasks because it sees the …

Optimize AreaDefinition.get_proj_coords when requesting dask arrays

---

.github/workflows/ci.yaml
.github/workflows/deploy.yaml

We no longer support Python 3.6  but wheels were being attempted. This PR removes Python 3.6 and tries Python 3.10. Let's see what happens...

Remove unsupported Python 3.6 from wheel building

---

.github/workflows/deploy.yaml
pyresample/ewa/dask_ewa.py
pyresample/test/test_dask_ewa.py

I've always tested the new algorithm with only one target, but once it was thrown into Polar2Grid we quickly realized that multiple targets was a problem. Luckily because of my map_blocks PR last week I knew to look at the dask task names for the issue.

Fix dask EWA code not creating unique dask task names for different target areas

---

pyresample/test/test_spherical.py
pyresample/test/test_swath.py

The unstable CI environment is failing. Likely due to small changes in numpy as the differences are on the order of 1/10th or 1/100th or less.

Allow less precision in tests to handle differences in unstable CI

---

pyresample/image.py

This PR moves the `bilinear` module import from the top of `image.py` to the function body of `ImageContainerBilinear.resample()`. 
`conda install -c conda-forge pyresample` does not install `xarray` and `zarr`. Thus, if one did not install `xarray` and `zarr` manually, running `import pyresample` will print out the following warning message:
```bash
(test) yunjunz:~>$ python -c "import pyresample"
/Users/yunjunz/tools/miniconda3/envs/test/lib/python3.10/site-packages/pyresample/bilinear/__init__.py:50: UserWarning: XArray and/or zarr not found, XArrayBilinearResampler won't be available.
warnings.warn("XArray and/or zarr not found, XArrayBilinearResampler won't be available.")
```
With this change, the top-level `import pyresample`, which calls `from pyresample import image`, won't call …

Move bilinear import to avoid unnecessary warning

---

pyresample/bilinear/_base.py

This fixes a DeprecationWarning coming from numpy:
```python
/root/mambaforge/envs/ci_env/lib/python3.10/site-packages/pyresample/bilinear/_base.py:220
`np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here. Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
```

Fix deprecated numpy data type usage in bilinear resampling

---

docs/source/conf.py

Update the copyright notice in the readthedocs documentation.

Update copyright note in documentation

---

.github/workflows/ci.yaml
pyresample/test/test_spherical.py

Drop Python 3.7 from the tested Python versions and add Python 3.10.

Change tested Python versions to 3.8, 3.9 and 3.10

---

pyresample/geometry.py
pyresample/test/test_files/areas.cfg
pyresample/test/test_geometry.py
pyresample/test/test_utils.py
pyresample/utils/rasterio.py

Pyproj has issued a warning for a long time now to tell the user to avoid using PROJ.4 strings and dictionaries as they are considered inaccurate as far as completely defining a projection (where WKT is now preferred). This PR updates one usage of this in `AreaDefinition.__eq__` so it compares the pyproj CRS objects directly instead of the PROJ.4 strings. This change does make equality a lot more strict, but probably in a good way. It now fails if your ellipsoid was defined in different ways or if axis order is different. This is very common with EPSG inputs.
This PR updates a few things to improve on this in the tests. It also includes a backwards incompatible change to the rasterio utilities to bring the argument name inline with AreaDefinition and be more accurate (`projection` instead …

Update AreaDefinition equality to use pyproj CRS

---

pyresample/gradient/__init__.py
pyresample/test/test_gradient.py

Helping out a colleague, I noticed that gradient search resampler doesn't work if a single-channel dataset (shape `(1, y, x)`) are used.
The error message was:
```python
Traceback (most recent call last):
File "/home/lahtinep/bin/test_akun_resamplays.py", line 40, in <module>
main()
File "/home/lahtinep/bin/test_akun_resamplays.py", line 31, in main
scn2 = scn.resample(suomi, resampler='gradient_search', fill_value=0)
File "/home/lahtinep/Software/pytroll/pytroll_packages/satpy/satpy/scene.py", line 906, in resample
self._resampled_scene(new_scn, destination, resampler=resampler,
File "/home/lahtinep/Software/pytroll/pytroll_packages/satpy/satpy/scene.py", line 822, in _resampled_scene
res = resample_dataset(dataset, destination_area, **kwargs)
File …
```

Fix gradient search for single band data

---

pyresample/area_config.py
pyresample/geometry.py
pyresample/test/test_files/areas.yaml
pyresample/test/test_geometry.py
pyresample/test/test_utils.py

It came up as a use case that sometimes it might be interesting to fix the resolution of a partially defined DynamicAreaDefinition (that is thus optimized upon freezing). Until this PR, the resolution was always computed in this case from the size of the lon/lat arrays, and any user-defined resolution was just ignored. This PR allows for example having a area like:
```yaml
omerc_bb_1000:
description: Oblique Mercator Bounding Box for Polar Overpasses
projection:
ellps: sphere
proj: omerc
optimize_projection: True
resolution: 1000
```

Fix DynamicAreaDefinition resolution handling for incomplete projection definitions

---

pyresample/ewa/_fornav_templates.cpp
pyresample/test/test_dask_ewa.py
pyresample/test/test_geometry.py

This hit us in a real world case recently and as far as I remember this was by design, but we have no idea why. It makes bad images. We (@kathys and myself) have decided to change the behavior to produce better images.

Fix EWA resampling not ignoring fill values with maximum_weight_mode

---

pyresample/bilinear/_base.py
pyresample/bilinear/xarr.py
pyresample/test/test_bilinear.py

The bilinear resampler didn't work for target areas that have invalid coordinates, like space pixels in the corners of full disk geostationary projections. This PR hopefully fixes this for data in `xarray.DataArray`s backed by `dask` arrays.
Tests are still needed.

Fix bilinear resampling to areas with invalid coordinates

---

setup.py

A request was recently posted on the python mailing list about including Cython as the language of your package in the setup.py metadata. This PR adds that classifier.

Add Cython classifier to package metadata

---

pyresample/bucket/__init__.py
pyresample/test/test_bucket.py

Implement get_abs_max on the BucketResampler class.

Implement get_abs_max on BucketResampler

---

pyresample/bilinear/_base.py
pyresample/bilinear/xarr.py
pyresample/test/test_bilinear.py

Resampling of 1D data with the Numpy-based bilinear resampler got broken when I did the big refactoring with common base for Numpy and XArray resamplers. This PR will eventually allow 1D data to be resampled with both.

Fix bilinear resampler for 1D data

---

pyresample/ewa/_fornav.pyx
pyresample/ewa/_ll2cr.pyx

I realized while debugging performance that none of the EWA cython code was releasing the GIL when it could (it is almost all non-python C++ code). ~This PR also refactors some code that couldn't be cleaned up with the older original versions of cython that were used when it was first developed.~ (nevermind the cleaner code won't work)

Add GIL releasing to EWA cython code

---

.github/workflows/deploy.yaml
pyresample/geometry.py
pyresample/test/test_geometry.py

While debugging some performance issues in my own software that uses pyresample I noticed that using a SwathDefinition in a dict can sometimes causes computation of the underlying dask arrays. This was unknown behavior to me but turns out to be expected. When a dict key hash matches one that already exists, Python's dict will do an `__eq__` check between the two keys to make sure they are actually the same object as it is possible for two different objects to produce the same hash. In our case, SwathDefinition hashes are based on the underlying dask arrays (in the case that dask arrays are used) to avoid hashing them as numpy arrays. In the cases where `__eq__` is called the entire dask array for lon and lat for both swath definitions are computed when compared to each other.
Side note: …

Fix SwathDefinition causing unnecessary dask computes when used as a dict key

---

pyresample/spherical.py
pyresample/test/test_spherical.py

The equality between two infinite coordinates was removed in 507925926b9c2d346aad449790dc29e7bb0daeaa through the unwrapping of the longitude returning a NaN instead of Inf in that case. This PR restores the previous behaviour.
Example of failing script:
```python
from satpy import Scene
from glob import glob
import os
from satpy.utils import debug_on
debug_on()
datadir = "/home/a001673/data/satellite/Meteosat-11/seviri/lvl1.5/2018/02/28/HRIT"
scn = Scene(filenames=glob(os.path.join(datadir, "*")),
reader='seviri_l1b_hrit',
)
composite = "overview"
scn.load([composite])
newscn = scn.resample("moll")
newscn.save_datasets(base_dir='/tmp', tiled=True, blockxsize=512, blockysize=512, driver='COG', overviews=[])
```

Fix infinite coordinates failing to be equal

---

.github/workflows/deploy.yaml
continuous_integration/build-manylinux-wheels.sh
setup.py

We were already doing 3.7-incompatible things. This just makes it official.

Remove Python 3.7 support

---

pyresample/_spatial_mp.py
pyresample/bilinear/_base.py
pyresample/bilinear/xarr.py
pyresample/bucket/__init__.py
pyresample/geo_filter.py
pyresample/geometry.py
pyresample/grid.py
pyresample/test/conftest.py
pyresample/test/test_bilinear.py
pyresample/test/test_geometry.py
pyresample/test/test_resamplers/test_nearest.py

For a long time we have used a shortcut when transforming lon/lat area coordinates to generic "lon/lat degrees" by checking if the CRS of that area is "geographic" and returning the original input coordinates. This is really only correct in the cases where the CRSes are the same. This shortcut was causing issues in nearest (and other) resamplers where if you resampled to an AreaDefinition with a shifted prime meridian (ex. at 180/-180). In these cases the resampling was using the non-shifted lon/lat coordinates which usually meant you got a black image as a result of resampling. This PR removes this shortcut.
By removing this shortcut this means that the utility/custom Proj class in `pyresample/_spatial_mp.py` is no longer needed as it doesn't actually do anything any more. I will remove …

Fix handling of lon/lat coordinates on CRS with prime meridian != 0

---

pyresample/bilinear/__init__.py

Include dask in list of potential missing imports

Fix import warning in bilinear resampler to mention dask

---

pyresample/geometry.py
pyresample/test/test_geometry.py

This PR fixes the hashing of definitions based on non contiguous arrays

Fix hashing of definitions for non contiguous arrays

---

pyresample/ewa/_legacy_dask_ewa.py
pyresample/ewa/dask_ewa.py

As described in https://github.com/pytroll/python-geotiepoints/pull/38 I discovered that the default `weight_delta_max` in the dask EWA code did not match the docstring. The docstring is correct for MODIS data and matches what has been in the EWA algorithm forever (it was originally written for MODIS code).
I really don't want to add a test for this.

Fix EWA default for 'weight_delta_max' to match docstring

---

pyresample/future/spherical/__init__.py
pyresample/future/spherical/point.py
pyresample/spherical.py
pyresample/test/test_sgeom/__init__.py
pyresample/test/test_sgeom/test_point.py
pyresample/test/test_spherical.py

This PR add the SPoint and SMultiPoint class of the future spherical geometry interface.

[Future Spherical Class] Add SPoint and SMultiPoint

---

pyresample/geometry.py
pyresample/test/test_geometry.py

This PR removes the presence of duplicate consecutive coordinates in the geostationary are bbox/polygon.
This currently leads to the creation of SArcs that are actually points, and also leads to cross-product operations that lead to cartesian [0,0,0] and thus vector norm = 0 and thus division by 0 when normalizing. 
Furthermore, it closes #474: when we retrieve 4 vertices we now get the 4 correct geos_area "extent" coordinates.

Fix for duplicate coordinates in bbox_lonlats for geostationary area 

---

pyresample/geometry.py
pyresample/test/test_geometry.py

I ran into this with some VIIRS data and some AVHRR data. In one case I had a couple rows/scans of data that had NaNs in them so some of the bbox coordinates were NaN. This resulted in bbox coordinates being returned, but being invalid (had NaNs). In another case the top couple scans of the swath were all NaNs so you'd get some hard to decipher error about NaN values. Sometimes these only made themselves obvious when you made a Boundary/Polygon and tried to do some calculation with them.
This PR fixes these cases or improves the error messages by removing any bbox points that have NaN for one of the coordinates.
CC @ghiggi

Fix bbox creation for SwathDefinitions with NaNs

---

pyresample/test/test_geometry.py

As reported in #484, test_area_def_geocentric_resolution fails with PROJ 9.1.1 because the tolerance is exceeded.

Tune tolerance to fix test failures with PROJ 9.1.1.

---

setup.py

This PR update the min version of pyproj to 3.0 as pyresample relies on it already.
The only test that I did was to manually install pyproj 3.0 and to make sure `import pyresample` does throw an error.

FIX: Update pyproj min version to 3.0.0

---

.github/workflows/ci.yaml
pyresample/ewa/_legacy_dask_ewa.py
pyresample/ewa/dask_ewa.py
pyresample/test/test_dask_ewa.py

Hopefully ends up resolving #481 or at least parts of it.

Fix intermittent EWA test failures

---

.github/workflows/deploy.yaml
pyresample/geometry.py
pyresample/gradient/__init__.py
pyresample/test/test_geometry.py
pyresample/test/test_gradient.py
setup.py

As described in #492 , this PR fixes problems in geostationary bbox computation

Fix geostationary bbox having inf values

---

pyresample/kd_tree.py
pyresample/test/test_kd_tree.py

There is something wrong while geocoding a wrapped interferograms in complex type due to `ComplexWarning`. The change would fix it as below.
https://github.com/insarlab/MintPy/issues/955#issuecomment-1423716672

Fix data type handling (complex) in nearest neighbor resampling

---

.github/workflows/ci.yaml
.github/workflows/deploy.yaml
continuous_integration/build-manylinux-wheels.sh
setup.py

It's what all the cool kids are doing.

Drop Python 3.8 support

---

pyresample/area_config.py
pyresample/geometry.py
pyresample/test/test_files/areas.yaml
pyresample/test/test_geometry/test_area.py
pyresample/test/test_geometry_legacy.py
pyresample/test/test_utils.py

After talking with @loreclem on slack, we decided that it should be OK to deprecate the functionality added by him via the `rotation` keyword argument in the AreaDefinition. As far as I know this functionality was not used by anyone (even Lorenzo doesn't use it anymore) and should be replaced by parameters to the CRS (projection) being defined for the area. Overall, I wanted to remove this to cleanup code that was/is likely not being used by anyone and only makes the code harder to maintain.
Note: This PR is based on #464 so it has a lot of commits and changes that will go away when that PR is merged.

Deprecate AreaDefinition 'rotation' argument

---

docs/source/swath.rst

Just found a couple of typos reading the docs.

Couple of small typos found in documentation.

---

pyresample/gradient/__init__.py
pyresample/resampler.py
pyresample/test/test_gradient.py
pyresample/test/test_resamplers/test_resampler.py

This implements a noop when source and destination areas are the same for gradient search instead of raising an error.

Fix gradient resampling to same area not working

---

pyresample/kd_tree.py
pyresample/test/test_utils.py
pyresample/test/utils.py
pyresample/utils/row_appendable_array.py

When applying `get_neighbour_info` to large target arrays with many segments it significantly slows down due to memcpys performed when concatenating segments. By allowing the user to pre-allocate result arrays these can be avoided resulting in significant speed ups. See also the linked issue.

Add pre-allocation option to `get_neighbour_info` to improve performance on large raster data

---

pyresample/area_config.py
pyresample/future/geometry/area.py
pyresample/geo_filter.py
pyresample/geometry.py
pyresample/gradient/__init__.py
pyresample/test/test_geometry/test_area.py
pyresample/test/test_gradient.py
pyresample/test/test_resample_blocks.py
pyresample/test/test_resamplers/test_resampler_registry.py
pyresample/utils/cf.py

This should resolve a majority of the warnings generated during pyresample and satpy tests. There are still many cases of tests using `area_def.proj_str == other_area.proj_str`, but we'll get to those later.

Ignore pyproj to_proj4 warning when converting an AreaDefinition to a string

---

pyresample/geometry.py
pyresample/gradient/__init__.py
pyresample/test/test_dask_ewa.py
pyresample/test/test_geometry/test_swath.py
pyresample/test/test_gradient.py

More PROJ and invalid value warnings that are raised during testing

Remove more warnings encountered during tests

---

README.md

The readme file has an outdated section on python versions - this PR removes that section.

Remove python versions tested note in documentation

---

.github/workflows/ci.yaml
.readthedocs.yml

I noticed that some of the RTD builds had warnings due to bad formatting, but the builds weren't failing. I'd like to know as soon as possible that something isn't building as expected. This sets the proper option for RTD.

Add configuration for readthedocs to fail on warnings

---

pyresample/geometry.py
pyresample/test/test_geometry_legacy.py
pyresample/test/test_gradient.py

Closes the new issue described in #517 where the user points out that they requested a resolution of 250.0 but the resulting `AreaDefinition` does not match that and actually changes between cases. This PR fixes this so in the cases where resolution is provided (and not shape) the resulting area should have `pixel_size_x/pixel_size_y` very very close to this value except for some floating point precision.

Fix DynamicAreaDefinition not preserving user's requested resolution

---

.github/workflows/deploy.yaml
continuous_integration/environment.yaml
docs/environment.yml
docs/source/conf.py
docs/source/howtos/configuration.rst
docs/source/howtos/index.rst
pyresample/__init__.py
pyresample/_config.py
pyresample/area_config.py
pyresample/future/geometry/area.py
pyresample/geometry.py
pyresample/test/conftest.py
pyresample/test/test_config/__init__.py
pyresample/test/test_config/test_feature_flags.py
pyresample/test/test_geometry/test_area.py
pyresample/test/test_gradient.py
pyresample/test/test_utils.py
pyresample/test/utils.py
pyresample/utils/cf.py
pyresample/utils/rasterio.py
setup.py

This is the first step of many to allow users a way of transitioning easily between pyresample 1.x and pyresample 2.x interfaces and objects. As a first step this PR adds a new `pyresample.config` object using `donfig` and includes a `features.future_geometries` boolean flag. This flag modifies utility functions like `create_area_def` to return a future `AreaDefinition` instead of the old/existing `AreaDefinition`. Along with some changes to imports users should be able to easily switch usage to the new geometry objects semi-easily (I think).
This also adds a `to_legacy()` method to the future area so it is easier to create the future area but return the legacy version.
As part of these changes I originally added an import in `pyresample/__init__.py` so that importing `AreaDefinition` and …

Add builtin 'config' object and 'features.future_geometry' toggle

---

pyresample/test/test_utils.py
pyresample/utils/proj4.py

Fix bug in `AreaDefinition.proj_str` where value-less parameters are given a value of `None`:
```
>>> ad = pyresample.AreaDefinition(
...     area_id='area_id',
...     description='description',
...     proj_id='tasmania_utm',
...     projection='+ellps=WGS84 +no_defs +proj=utm +south +towgs84=0,0,0 +type=crs +units=m +zone=50',
...     area_extent=(701609.0, 5127659.0, 901609.0, 5327659.0),
...     height=10,
...     width=10,
... )
>>> 
>>> ad.proj_str
(path to venv)/lib/python3.11/site-packages/pyproj/crs/crs.py:1286: UserWarning: You will likely lose important projection information when converting to a PROJ string from another format. See: https://proj.org/faq.html#what-is-the-best-format-for-describing-coordinate-reference-systems
proj = self._crs.to_proj4(version=version) …
```

Handle value-less parameters in `proj4_dict_to_str`

---

pyresample/geometry.py
pyresample/test/test_geometry/test_area.py

Allow cropping non-geos areas

---

pyresample/_spatial_mp.py
pyresample/geometry.py
pyresample/test/test_geometry/test_area.py
pyresample/utils/proj4.py

This PR switches from using pyproj's old `Proj` interface to the newer `Transformer` class. Transformers should have better overall handling of more complex projection transformation.
One note is that I did have to add special handling of CRSes with prime meridian shifts (`+pm=180`) to make `get_lonlats` return what it used to. That is, lon/lats on a prime meridian 0 CRS.
CC @larsbuntemeyer

Migrate usages of pyproj Proj to pyproj Transformer

---

pyresample/area_config.py
pyresample/future/geometry/area.py
pyresample/test/conftest.py
pyresample/test/test_geometry/test_area.py
pyresample/test/test_resamplers/test_nearest.py
pyresample/utils/rasterio.py

This was discussed in a previous PR regarding cleaning up AreaDefinitions. The basic idea is to reduce the number of arguments passed to an AreaDefinition to keep the interface a little cleaner and simpler. This PR does this by grouping the width and height arguments into a single "shape" tuple.
This also makes it easier to create AreaDefinitions with more than 2 dimensions in the long long term.

Replace width/height in future AreaDefinition with "shape" argument

---

pyresample/geometry.py

This PR replaces the `frequency` argument used in many `*Definition` method with the more correct `bbox_shape`.
Historically, the name was correct, but a behaviour-changing commit (19e1ea5) it became inaccurate.

Replace and deprecate frequency arg for bbox methods

---

pyresample/test/test_bilinear.py

Fix tests on i386

---

pyresample/area_config.py

Removes an unnecessary and likely unused PROJ.4 string -> dict conversion in `get_area_def`. See #547 for more info.

Remove unnecessary proj4 argument parsing from get_area_def

---

pyresample/utils/proj4.py

This shortcut exists in the code to avoid having to convert a CRS to a PROJ.4 dict if it isn't needed. I'm not sure how or why, but `.prime_meridian` is not an integer, it is an object, and comparing it to `== 0` will always give False from what I'm seeing. I should have always been using `.prime_meridian.longitude`.
I'm not exactly sure how to test this as it is just a performance thing (avoid unnecessary conversions). The end result should have always been the same.

Fix shortcut for prime meridian checks

---

.github/workflows/ci.yaml
continuous_integration/environment.yaml
pyresample/test/test_utils.py

Add Python 3.12 to CI tests

---

docs/source/howtos/configuration.rst
pyresample/_caching.py
pyresample/_config.py
pyresample/future/geometry/_subset.py
pyresample/geometry.py
pyresample/test/conftest.py
pyresample/test/test_geometry/test_area.py
versioneer.py

While profiling some Satpy computations (ABI full disk -> nearest neighbor resampling) I noticed that a decent amount of time at the beginning of processing was spent outside of dask computations and was using a single core. After some print-statement debugging I discovered it was Satpy's `reduce_data` functionality and the `AreaDefinition.get_area_slices` that was taking the most time. The majority of that time is spent in the polygon intersection operation to see if the two areas being used intersect and where.
This PR adds a decorator and a couple configuration settings for caching the results of `AreaDefinition.get_area_slices` to on-disk JSON files. For my testing case I was seeing about ~10-12 seconds being used for `get_area_slices` per area definition pair. I was using 2 …

Add optional caching to AreaDefinition.get_area_slices

---

pyresample/test/test_area_config.py
pyresample/test/test_image.py
pyresample/test/test_kd_tree.py
pyresample/test/test_plot.py
pyresample/test/test_swath.py
pyresample/test/test_utils.py
pyresample/test/utils.py

Remove `__file__` usage in test units for `test_files` path.

Remove `__file__` usage in test units for `test_files` path

---

pyresample/utils/cf.py

This PR removes a warning when getting actual projection details that are needed for CF by using `to_cf()` instead of `to_dict()`. This is part of Satpy reader cleanup started in https://github.com/pytroll/satpy/pull/2689

Suppress PROJ4 warning about losing projection by using `to_cf()` instead of `to_dict()`

---

pyresample/test/conftest.py
pyresample/test/test_formatting.py
pyresample/test/test_geometry/conftest.py

No need to create them for every test. Additionally this fixes a test failure caused by one PR refactoring the imports of another that were both merged at essentially the same time.

Switch test area fixtures to session-scoped

---

pyresample/area_config.py
pyresample/test/test_area_config.py

If a user has a typo or some other unused parameter in an area YAML definition then pyresample silently ignores it and the user is left confused as to why things aren't working as expected. This PR fixes this by producing a UserWarning in these cases.
I could make this an error but I feel that limits the future flexibility and maintainability of the YAML reading. I could also make a configuration (`pyresample.config`) parameter that controls whether this is a warnings or error...or maybe just another keyword argument, but I'm not sure we need any more kwargs for these functions.
TODO: I'd like to rework some of the metadata handling in the future area definitions. I might not do that in this PR as it is decently separate. I noticed while working on this that any unused kwarg is put into …

Fix area definition YAML not warning on typos

---

pyresample/_spatial_mp.py
pyresample/bilinear/xarr.py
pyresample/bucket/__init__.py
pyresample/future/resamplers/nearest.py
pyresample/geometry.py
pyresample/kd_tree.py
pyresample/utils/proj4.py

Without the `meta=` keyword argument to `da.map_blocks` dask will call the mapped function with fake/representative arguments to try to determine what the returned array and dtype are. This PR adds this kwarg to avoid this unnecessary execution of the function.
This very likely won't have any effect on performance, but it helps with debugging and is an unnecessary call if you forget it.

Add missing meta keyword arguments on all dask map_blocks calls

---

.github/workflows/deploy.yaml
pyproject.toml

Temporary solution to build wheels that are compatible with numpy 1 and numpy 2. Once numpy 2 is released these extra lines can be removed.

Build wheels against numpy 2

---

.github/workflows/ci.yaml
pyresample/grid.py
pyresample/kd_tree.py
pyresample/spherical.py
pyresample/test/test_gradient.py
pyresample/test/test_kd_tree.py
pyresample/test/test_resample_blocks.py
pyresample/utils/row_appendable_array.py

I need to build deps from github source with the unstable numpy and not in a sandboxed virtualenv. Passing `--no-build-isolation` should fix this.

Add no build isolation to unstable CI installs

---

pyresample/area_config.py
pyresample/test/test_area_config.py
pyresample/test/test_files/areas.yaml

Broken in #577. I accidentally stopped passing/parsing `optimize_projection` to `DynamicAreaDefiniton` objects parsed from YAML. This was first noticed in Satpy's tests. This PR fixes it. As stated in #577, I'd still like to follow this up with a PR to move metadata from YAML being any random kwarg to being an explicit `attrs` key.

Fix optimize_projection handling in YAML parsing

---

pyresample/future/geometry/swath.py
pyresample/test/conftest.py
pyresample/test/test_geometry/test_swath.py

This PR adds attrs to the future swath definition.

Add attrs to future swath definition

---

.github/workflows/deploy.yaml
pyproject.toml

Numpy 2 API should be stable now. Let's release some wheels with numpy 2.0rc1...

Build against numpy 2.0rc1

---

.github/workflows/ci.yaml
.github/workflows/deploy.yaml

Remove unnecessary zarr dependency causing complications in unstable CI (it's annoying to install all of its dependencies manually).

Fix unstable CI

---

.github/workflows/ci.yaml
pyresample/geometry.py
pyresample/test/test_geometry/test_area.py

An attempt to fix https://github.com/ssec/polar2grid/issues/691
Basically, current bounding operations via `get_area_slices` have trouble when the resulting lon/lat extents match *almost* exactly with the source area definition. This PR should fix a couple important bugs in the array index retrieval methods of the AreaDefinition:
1. Floating point precision issues where a X coordinate that is just outside the area (a float precision different) can still be considered part of the area (not masked).
2. Not including -0.5 to 0.0 pixel indexes as "0" (it is the left most part of the left most pixels.
3. Including an extra 0.5 pixels on the right of the area.
Locally I see one failure where my particular approach has changed the underlying value for elements that are masked and this test …

Fix AreaDefinition array index methods mishandling outer edge values

---

pyresample/bucket/__init__.py
pyresample/test/test_bucket.py

This PR adds support for `fill_value` and `set_empty_bucket_to` in BucketResampler `get_sum`. This is a nice feature, but most importantly it fixes the satpy `bucket_sum` interface.
Closes https://github.com/pytroll/satpy/issues/2805, closes https://github.com/pytroll/satpy/issues/1746, closes https://github.com/pytroll/pyresample/issues/354

Add support for `fill_value` and `set_empty_bucket_to` in BucketResampler `get_sum`

---

pyresample/_formatting_html.py
pyresample/static/css/style.css

This is a quick fix for #609. It just sets things like resolution and width/height to Na in the case of 1D lat/lon arrays so the html representation does not break.
It also does some quick fixing of formatting issues I noticed.

Fix SwathDefinition html representation error when lons/lats 1D

---

pyresample/_formatting_html.py
pyresample/utils/cartopy.py

In case of geostationary full disc plots the boundary of the cartopy CRS needs to be the actual full disc otherwise ocean/land features spill over.
Since the `to_cartopy_crs` method in pyresample uses a custom Projection class this is a hot fix using code from the Cartopy `Geostationary` class.

Fix spill over of ocean/and features in cartopy plots in case of geostationary full disc plot.

---

.github/PULL_REQUEST_TEMPLATE.md
pyresample/geometry.py
pyresample/test/test_geometry/test_area.py

Satpy unstable environment started failing and regular environments will start failing too when conda-forge has numpy 2.1.0 available.
Starting with numpy 2.1.0 the numpy function `histogram_bin_edges` will raise a `ValueError` if the array you give it can't be split into the number of buckets you request (default 10). This happens when the elements of an array are so close together (near floating point precision) that numpy can't possibly split things into N buckets. There error you get is:
```
E               ValueError: Too many bins for data range. Cannot create 10 finite-sized bins.
```
This PR works around this by adding a try/except to the call and just returning the two elements of the input array. As far as I can tell this is basically equivalent.

Fix geocentric_resolution compatibility with numpy 2.1.0

---

pyresample/_formatting_html.py
pyresample/geometry.py
pyresample/test/test_formatting.py

These changes help control how AreaDefinitions and others are represented when plotted for sphinx documentation (specifically Satpy). See https://github.com/pytroll/satpy/issues/2864 for more information. No TDD on this one.
CC @BENR0

Allow overriding area repr map section HTML

---

pyresample/gradient/__init__.py
pyresample/gradient/_gradient_search.pyx
pyresample/test/test_gradient.py

Resampling `float32` swath data resulted in `float64` output. This is a simple fix for this data type promotion.

Fix dtype for swath -> area resampling with gradient search

---

.github/workflows/ci.yaml
.gitignore
pyresample/geometry.py
pyresample/test/test_geometry/test_area.py

This PR adds the possibility to use the bounding box attribute of the swathdefinition to freeze a dynamic area definition.

Make use of bounding_box for area freezing when available

---

setup.py

Apparently `setuptools` is not required at runtime

Move setuptools to setup_requires

---

.github/workflows/deploy.yaml
pyresample/_formatting_html.py

Fix for resolution stating SSP in non geos cases

---

.github/workflows/ci.yaml
pyresample/gradient/__init__.py
pyresample/gradient/_gradient_search.pyx
pyresample/test/test_gradient.py

This PR fixes #642.
The symptom was that every other line, or all lines, of chunks that were on the edges of a geos disc would be nans. That was because the cursor in the gradient search algorithm was not moved along x when a pixel was skipped because of invalid target coordinates.

Fix bug that would add spurious nan lines in gradient search

---

.github/workflows/ci.yaml
.github/workflows/deploy.yaml
.readthedocs.yml
continuous_integration/environment.yaml
docs/environment.yml
pyproject.toml
pyresample/_compat.py
pyresample/geometry.py
pyresample/utils/__init__.py
setup.py

This PR adds support for python 3.13. This was triggered by the rebuild of pyresample for 3.13 in conda forge.

Drop support for Python <3.11

---

pyresample/ewa/_ll2cr.pyx
pyresample/ewa/ewa.py
pyresample/test/test_ewa_ll2cr.py
versioneer.py

The pyproj `Proj` object is deprecated and is not as accurate/explicit as the `Transformer` interface. I did some of these changes in my #645 branch, but decided that these changes should be their own PR. Unfortunately this also meant that I changed the low-level interfaces of ll2cr to accept a source CRS and a target CRS instead of just the target projection information.

Update EWA pyproj Proj usage to Transformer

---

pyresample/geometry.py
pyresample/test/test_geometry/test_area.py

This PR fixes dynamic areas not preserving epsg code when freezing.

Fix dynamic area freezing not preserving epsg code

---

pyresample/area_config.py

Using `logging.X("message")` uses the root logger which is hard to control/filter. This PR creates a logger object unique to the `pyresample/area_config.py` module.

Fix area_config using root logger

---

pyresample/utils/proj4.py

See https://github.com/dask/dask/pull/11952
I used `name=` because `token=` was deprecated. This has been reverted in dask now and the desired behavior of defining a task name prefix is through the `token` kwarg to `map_blocks`.

Revert change of map_blocks name= kwarg in favor of token=

---

pyresample/boundary/legacy_boundary.py
pyresample/test/test_boundary/test_legacy_boundary.py

In a real world case identified by @spruceboy, if a 32-bit coordinate is given to `AreaBoundary` (or any boundary class) that is exactly at 90 degrees north, the conversion to radians and then validity checks in the spherical polygon class will raise an error.
```python
File "/opt/cspp/polar2grid_v_3_1/libexec/python_runtime/lib/python3.11/site-packages/pyresample/spherical.py", line 571, in aedges
yield Arc(SCoordinate(lon_start, lat_start),
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/opt/cspp/polar2grid_v_3_1/libexec/python_runtime/lib/python3.11/site-packages/pyresample/spherical.py", line 131, in __init__
lon, lat = _check_lon_lat(lon, lat)
^^^^^^^^^^^^^^^^^^^^^^^^
File "/opt/cspp/polar2grid_v_3_1/libexec/python_runtime/lib/python3.11/site-packages/pyresample/spherical.py", line 119, in …
```

Fix boundaries losing precision for accurate polygon calculations
