pyresample/plot.py
Make possible to indicate which colormap to use when plotting image (add 'cmap' kwarg).
=> Add option to choose colormap

pyresample/spherical_geometry.py, pyresample/test/test_spherical_geometry.py
- Fix computation of polygon area for R != 1
- Do not snap angles when computing polygon areas in order to prevent negative values 
Discussion: https://github.com/pytroll/pyresample/issues/48
=> Fix polygon area

.travis.yml, docs/areas.yaml, docs/source/geo_def.rst, pyresample/geometry.py, pyresample/test/test_files/areas.yaml, pyresample/test/test_utils.py, pyresample/utils.py, setup.py
Support yaml format for the area files
=> Add support for areas in yaml format

docs/source/geo_def.rst, pyresample/geometry.py, pyresample/test/test_geometry.py
=> Rename `proj_x/y_coords` to `projection_x/y_coords`

.travis.yml, pyresample/kd_tree.py
=> Fix write to mask affecting original mask in future versions of numpy

pyresample/geometry.py, pyresample/kd_tree.py, pyresample/test/test_kd_tree.py
This pull request add a new resampler class that is capable of resampling xarray's DataArrays.
Along with this, we added a couple of functions to generate lon-lats and projection coordinates as dask arrays for lazy evaluation.
=> Support resampling of xarray.DataArrays

pyresample/utils.py
proj4 strings converted to dictionary now consistent with other code (no longer has leading '+')
new logic for reporting projection semi-major / semi-minor axes ('a', 'b') based on information in proj4
=> Utils edits for retreiving projection semi-major / semi-minor axes

.travis.yml, appveyor.yml, pyresample/geometry.py, pyresample/test/test_utils.py, pyresample/utils.py
Includes fixes for dynamic area definitions proj_id and
small performance improvement for projection coordinate generation
I know it isn't the best that I included some of these changes in one PR, but I had them sitting around and thought I needed to do it.
=> Add proj4_dict_to_str utility function

pyresample/geometry.py, pyresample/image.py, pyresample/test/test_rotation.py, pyresample/utils.py
Added ROTATION in an area definition in order to rotate an image after resampling.
=> Added ROTATION in an area definition

.travis.yml, pyresample/geometry.py, pyresample/kd_tree.py, pyresample/test/test_geometry.py
Removes annoying log message when xarray/dask is missing
=> Add hash method to AreaDefinition

pyresample/geometry.py, pyresample/kd_tree.py, pyresample/utils.py
This PR fixes multidimension xarray.DataArray resampling
=> [WIP] Feature multiple dims

pyresample/kd_tree.py
Please make the PR against the `develop` branch.
=> Fix xarray resampling for partially invalid source datasets

pyresample/geometry.py
Support dynamic areas for arbitrary projections. Tested with laea, merc, and stere (last one doesn't look good)
=> Add support for dynamic resampling for most projections

README.md
Please make the PR against the `develop` branch.
=> Update README to include correct versions of python tested

appveyor.yml, pyresample/geometry.py, pyresample/test/test_geometry.py, setup.py
Please make the PR against the `develop` branch.
=> Fix area equality to support np.nan, xarray and dask

pyresample/__init__.py, pyresample/geometry.py, pyresample/kd_tree.py
Please make the PR against the `develop` branch.
=> [WIP] Remove closures to allow memory to be freed

pyresample/geometry.py
This PR centralises the hashing of geometric definitions, and makes it deterministic for python > 3.3
=> Implement Deterministic hashing

pyresample/kd_tree.py
Moreover this speeds up processing for smaller target areas
=> Simplify get_sample_from_neighbour_info method

pyresample/geometry.py, pyresample/test/test_geometry.py, pyresample/utils.py
=> Fix proj4_string to support valueless arguments

pyresample/geometry.py, pyresample/test/test_geometry.py
=> Fix the omerc bb to use gamma instead of no_rot

pyresample/image.py
This is a minor fix : a message for a raised exception is badly formed
=> fix a syntax error

docs/source/geo_def.rst, pyresample/geometry.py, pyresample/test/test_geometry.py, pyresample/test/test_grid.py, pyresample/test/test_utils.py, pyresample/utils.py
Recreation of #139 because I accidentally merged it when I pushed to the wrong remote.
=> Fix area parsing code to convert PROJ.4 parameters to float if possible

pyresample/geometry.py, pyresample/test/test_files/areas.cfg, pyresample/test/test_geometry.py, pyresample/test/test_utils.py, pyresample/utils.py
Add converter from def to yaml
=> Add converter from def to yaml

pyresample/kd_tree.py
I was running in to this issue with Geo2Grid a lot and users doing custom area definitions a lot. One user got it down to a very simple use case that I was able to narrow down to only pyresample. In certain cases with certain chunk sizes, pyresample would hang when things were being computed at the end of processing. If your input data had a chunk size of 1024 and your output/target area was larger than that then computation for nearest neighbor resampling would never complete.
I got it down to the fix in this PR. The main issue was that dask arrays were being used *and* computed inside of a function that was already delayed (via `blockwise`). I think this was causing a weird recursion issue for dask and ended up producing a deadlock. The fix is to use dask only if the input data is a …
=> Fix dask race condition in KDTree resampling

pyresample/geometry.py
Dask can't serialize internal functions on distributed systems. This causes serialization errors when computing dask arrays on distributed schedulers (multiprocess or cluster).
=> Fix aggregate method using non-serializable internal function

docs/source/plot.rst
Signed-off-by: Adam Dybbroe <Adam.Dybbroe@smhi.se>
=> fix bug in plot example code

pyresample/geometry.py, pyresample/test/test_geometry.py
=> Make optimal bb computation work with numpy arrays

pyresample/geometry.py, pyresample/test/test_geometry.py
Fix calculation of new resolution in SwathDefinition.aggregate.
=> Fix resolution computation for SwathDefinition.aggregate

.travis.yml, appveyor.yml, docs/source/index.rst, docs/source/installation.rst, pyresample/area_config.py, pyresample/test/__init__.py, pyresample/test/test_bilinear.py, pyresample/test/test_bucket.py, pyresample/test/test_data_reduce.py, pyresample/test/test_ewa_fornav.py, pyresample/test/test_ewa_ll2cr.py, pyresample/test/test_geometry.py, pyresample/test/test_gradient.py, pyresample/test/test_grid.py, pyresample/test/test_image.py, pyresample/test/test_kd_tree.py, pyresample/test/test_plot.py, pyresample/test/test_spatial_mp.py, pyresample/test/test_spherical.py, pyresample/test/test_spherical_geometry.py, pyresample/test/test_swath.py, pyresample/test/test_utils.py, pyresample/test/utils.py, pyresample/utils/_proj4.py, pyresample/utils/_rasterio.py, setup.py
=> Switch to pytest for CI and remove Python <3.4 support

azure-pipelines.yml
Some work on VisPy pointed out that the Azure Windows tasks can be simplified.
=> Simplify Azure Windows builds

pyresample/geometry.py, pyresample/test/test_geometry.py
This PR is a retry of https://github.com/pytroll/pyresample/pull/277 which was merged so that the actual fix wasn't included. The unit test is there in `master`, so no new tests added.
=> Check the source area orientation before defining slices

MANIFEST.in, setup.py
Install test data to be able to run the test suite also when the package is installed.
=> Add missing test data to package

pyresample/_spatial_mp.py, pyresample/area_config.py, pyresample/bilinear/__init__.py, pyresample/boundary.py, pyresample/data_reduce.py, pyresample/ewa/__init__.py, pyresample/ewa/_fornav.pyx, pyresample/ewa/_ll2cr.pyx, pyresample/geo_filter.py, pyresample/geometry.py, pyresample/grid.py, pyresample/image.py, pyresample/kd_tree.py, pyresample/plot.py, pyresample/spherical.py, pyresample/spherical_geometry.py, pyresample/test/test_bucket.py, pyresample/test/test_ewa_fornav.py, pyresample/test/test_ewa_ll2cr.py, pyresample/test/test_geometry.py, pyresample/test/test_kd_tree.py, pyresample/test/test_spherical.py, pyresample/test/test_spherical_geometry.py, pyresample/test/test_swath.py, pyresample/test/utils.py, pyresample/utils/__init__.py, pyresample/utils/cartopy.py, pyresample/utils/proj4.py, pyresample/version.py, versioneer.py
@arpm Sorry I had to close your PR #219, git wasn't cooperative today.
I opened this one instead, where I tried to merge your commit with the current master. I hope I haven't lost your work in the process.
=> Switch docstrings to Google style

pyresample/spherical.py
Clarify the documentation for SphPolygon.area.
=> Clarify SphPolygon.area documentation

.github/workflows/deploy.yaml, continuous_integration/build-manylinux-wheels.sh
=> Add Python 3.11 to wheel building

.pre-commit-config.yaml, pyresample/area_config.py, pyresample/bilinear/__init__.py, pyresample/bilinear/_base.py, pyresample/bilinear/_numpy_resampler.py, pyresample/bilinear/xarr.py, pyresample/boundary.py, pyresample/future/resamplers/nearest.py, pyresample/future/resamplers/registry.py, pyresample/geometry.py, pyresample/gradient/__init__.py, pyresample/image.py, pyresample/kd_tree.py, pyresample/plot.py, pyresample/spherical_geometry.py, pyresample/test/test_geometry/test_area.py
This resolves pre-commit flake8 warnings.
=> Add stacklevel to all pyresample warnings

pyproject.toml
This PR add NPY to ruff rules and fixes a couple of deprecated ruff options
=> Add NPY to ruff rules
